### ISSUE TITLE
Plugin nie działa 

### ISSUE THREAD

**Issue by eko5** [jakzal/plugin.video.tvseriesonlinepl#1]
plugin do kodi nie działa prawidłowo , mam na myśli iż po wyszukaniu serialu nie uruchamia listy serwisów z linkami do uruchomienia . A więc co za tym idzie nie uruchamia serialu . Czy wtyczka jest rozwijana ??

**Comment by jakzal** [comment]
Nie uzywalem wtyczki przez ostatnie kilka tygodni, a testy sa uruchamiane tylko przy zmianach kodu, wiec nie zauwazylem, ze zmiany na stronie zepsuly wtyczke. Spojrze na to wieczorem.

**Comment by jakzal** [comment]
Naprawione w v1.0.3: https://github.com/jakzal/plugin.video.tvseriesonlinepl/archive/v1.0.3.zip

Dziala, jednak prosze pamietac, ze to jednak tylko prototyp. Wiele odtwarzaczy nie jest wspieranych (wspieram tylko te obslugiwane przez addon [UrlResorver](http://kodi.wiki/view/Add-on:Urlresolver) jak vidto.me).
